project: "tahoe-lafs"
default_repourl: "https://github.com/tahoe-lafs/tahoe-lafs"
allowed_hosts:
  "github.com":
      schemes: &schemes
        - "http"
        - "https"
      users: &users
        - "tahoe-lafs"
        - "warner"
        - "zooko"
        - "daira"
        - "leif"
        - "david415"
        - "exarkun"
        - "meejah"
        - "LeastAuthority"
  "tahoe-lafs.org":
      users: *users
      schemes: *schemes
